import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
await import("./build-ui.mjs");
await import("./build-notices.mjs");
const { createPlugin } = await import("./plugin.mjs");
const output=(await build({entryPoints:["plugin.mjs"],bundle:true,write:false,platform:"browser",format:"iife",globalName:"KanbanPlugin",minify:true,target:"es2022",legalComments:"inline"})).outputFiles[0].text;
const delegates=["appOption","noteOption"].map(type=>`${type}:{${Object.keys(createPlugin()[type]).map(name=>`${JSON.stringify(name)}:async function(...args){const p=this._get();return p[${JSON.stringify(type)}][${JSON.stringify(name)}].apply(p,args);}`).join(",")}}`);
for(const type of ["renderEmbed","onEmbedCall"])delegates.push(`${type}:async function(...args){const p=this._get();return p.${type}.apply(p,args);}`);
const code=`{_instance:null,_get(){if(!this._instance){${output}\nthis._instance=KanbanPlugin.createPlugin();}return this._instance;},${delegates.join(",")}}`;
const note="# Markdown Kanban (development)\n\n| name | Markdown Kanban |\n| --- | --- |\n| icon | view_kanban |\n| description | A Kanban board backed by your note's headings and tasks. |\n\n```javascript\n"+code+"\n```\n\n"+await readFile("THIRD_PARTY_NOTICES.md","utf8");
await writeFile("dist/plugin.js",code);
await writeFile("dist/PLUGIN_NOTE.md",note);
await writeFile("dist/plugin-manifest.json",JSON.stringify({version:"0.1.0",bytes:Buffer.byteLength(code),sha256:createHash('sha256').update(code).digest('hex'),fullHostVerified:false},null,2)+"\n");
console.log(`Built development plugin (${Buffer.byteLength(code)} bytes).`);
